"""create_initial_schema_with_enhanced_task_fields

Revision ID: a03f754660d4
Revises: 
Create Date: 2025-11-19 00:56:40.856303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a03f754660d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('task', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('tags', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'tags')
    op.drop_column('task', 'end_date')
    op.drop_column('task', 'start_date')
    op.drop_column('task', 'status')
    # ### end Alembic commands ###
